print "hello world"
print "hihihihihihi"
print "hello"
print "this is awesome"
print "merging files is magical"
print "and tough to understand too"
print "though i still need to learn a bit about it"

print "so if i try to merge like this then"
print "still trying to understand"
